const express=require("express")
const router=express.Router()
const isAuth = require("../middlewares/IsAuth")
const { placeorder, getuserorders, getownerorders, updateorderstatus, getdelassignment, acceptdelivery, getcurrentassiorder, getorderbyid, senddelotp, verifydelotp } = require("../controller/OrderController")
router.post("/placeorder",isAuth,placeorder)
router.get('/userorders',isAuth,getuserorders)
router.get("/ownerorders",isAuth,getownerorders)
router.post("/updatestatus/:orderId/:shopId",isAuth,updateorderstatus)
router.get("/getassignment",isAuth,getdelassignment)
router.post("/acceptorder/:assigmentId",acceptdelivery)
router.get("/getdelorder",isAuth,getcurrentassiorder)
router.get("/getorderbyid/:orderId",getorderbyid)
router.post("/senddelotp",isAuth,senddelotp)
router.post("/verifydelotp",isAuth,verifydelotp)
module.exports=router   